GuiApps.Web/Models/BookViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GuiApps.Model;

namespace GuiApps.Web.Models
{
    public class BookViewModel
    {
        public int Id;
        public string Name;
        public string Author;
        public string Genre;
        public int Year;
    }

    public class Mapper
    {
        public static BookViewModel MapBook(Book book)
        {
            return new BookViewModel
            {
                Id = book.Id,
                Name = book.Name,
                Author = book.Author, 
                Genre = book.Genre, 
                Year = book.Year
            };
        }
    }
}

GuiApps.Web/Models/ErrorViewModel.cs
using System;

namespace GuiApps.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GuiApps.Web/Controllers/BookController.cs
using System;
using System.Linq;
using GuiApps.Model;
using GuiApps.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace GuiApps.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _repository;

        public BookController(IBookRepository repository)
        {
            _repository = repository;
        }

        // GET: Book
        public ActionResult Index()
        {
            var vm = _repository.SelectAll().Select(Mapper.MapBook);
            return View("List", vm);
        }

        // GET: Book/Details/5
        public ActionResult Details(int id)
        {
            var item = _repository.Get(id);
            var vm = Mapper.MapBook(item);
            return View(vm);
        }

        // GET: Book/Create
        public ActionResult Create()
        {
            _repository.Create(new Book("<empty>", "<empty>", "<empty>", 0));
            return RedirectToAction(nameof(Index));
        }

        // GET: Book/Edit/5
        public ActionResult Edit(int id)
        {
            var item = _repository.Get(id);
            var vm = Mapper.MapBook(item);
            return View(vm);
        }

        // POST: Book/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                collection.TryGetValue(nameof(BookViewModel.Name), out var name);
                collection.TryGetValue(nameof(BookViewModel.Author), out var author);
                collection.TryGetValue(nameof(BookViewModel.Genre), out var genre);
                collection.TryGetValue(nameof(BookViewModel.Year), out var year);
                var item = new Book(id, name, author, genre, Convert.ToInt32(year));
                _repository.Update(item);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(HomeController.Error), "Home");
            }
        }

        // GET: Book/Delete/5
        public ActionResult Delete(int id)
        {
            _repository.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        // POST: Book/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                _repository.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(HomeController.Error), "Home");
            }
        }
    }
}

GuiApps.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using GuiApps.Web.Models;

namespace GuiApps.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GuiApps.Web/Views/Book/Details.cshtml
@model GuiApps.Web.Models.BookViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>BookViewModel</h4>
    <hr />
    <dl class="row">
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
    <p>Название: @Model.Name</p>
    <p>Автор: @Model.Author</p>
    <p>Жанр: @Model.Genre</p>
    <p>Год: @Model.Year</p>
</div>

GuiApps.Web/Views/Book/Edit.cshtml
@model GuiApps.Web.Models.BookViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>BookViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="@nameof(Model.Name)"></label>
                <input type="text" name="@nameof(Model.Name)" value="@Model.Name" />
            </div>
            <div class="form-group">
                <label for="@nameof(Model.Author)"></label>
                <input type="text" name="@nameof(Model.Author)" value="@Model.Author" />
            </div>
            <div class="form-group">
                <label for="@nameof(Model.Genre)"></label>
                <input type="text" name="@nameof(Model.Genre)" value="@Model.Genre" />
            </div><div class="form-group">
                <label for="@nameof(Model.Year)"></label>
                <input type="text" name="@nameof(Model.Year)" value="@Model.Year" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GuiApps.Web/Views/Book/List.cshtml
@model IEnumerable<GuiApps.Web.Models.BookViewModel>

@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Author</td>
            <td>@item.Genre</td>
            <td>@item.Year</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

GuiApps.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GuiApps.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GuiApps.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GuiApps.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - GuiApps.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>